# Cấu hình các mô hình
defaults:
  - model: logistic_regression 
  - experiment: base

# Cấu hình đường dẫn
data:
  raw_data: "data/raw/creditcard.csv"
  processed_data: "data/processed/cleaned_data.c
  test_size: 0.2
  random_state: 42
  target: Class

features:
  amount_col: Amount
  time_col: Time
  log_amount_col: Amount_Log
  hour_col: Hour
