# Cấu hình các mô hình
defaults:
  - data: default
  - features: built_features_default
  - model: logistic_regression 
  - experiment: base

# Cấu hình dự án
project:
  name: credit-card-fraud-detection
  random_seed: 42
